package game.systems.interrupt;

public enum InterruptCase {
	CROWDFUND,
	CROWDFUND_COUNTER,
	CROWDFUND_COUNTER_CHALLENGE_LOSS,
	VOIDOUT,
	PRINT_MONEY,
	PRINT_MONEY_CHALLENGE_LOSS,
	ORDER_HIT,
	FORCED_HIT,
	ORDER_HIT_COUNTER, //aka Decoy
	ORDER_HIT_CHALLENGE_LOSS,
	ORDER_HIT_COUNTER_CHALLENGE_LOSS, //aka Decoy challenge loss
	SCRAMBLE_IDENTITY,
	SCRAMBLE_SELECT,
	SCRAMBLE_IDENTITY_CHALLENGE_LOSS,
	RAID,
	RAID_COUNTER,
	RAID_COUNTER_CPT,
	RAID_COUNTER_NOPS,
	RAID_CHALLENGE_LOSS,
	RAID_COUNTER_CHALLENGE_LOSS;
}
